
[greenclip]
  blacklisted_applications = []
  static_history = [
    "get transport obfs4 > bridges@torproject.org",
    "dm-tool lock"
  ]
  enable_image_support = false
  history_file = "/tmp/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 50
  max_selection_size_bytes = 0
  trim_space_from_selection = false
  use_primary_selection_as_input = false
